### ISSUE TITLE
Increased gateway information and reporting

### ISSUE THREAD

**Issue by danielknox** [brocaar/chirpstack-network-server#327]
Hi, this is a feature request.

It would be useful if gateways that have been registered to an organisation, via the app-server, can raise an alert (email, etc.) if they have not been seen for a user definable length of time. Similarly increased reporting, to help identify misuse from other organisations nodes, would be useful - this detail could include common spread factors, frequencies and top nodes within certain periods.

This will help improve and encourage gateway management via the network server.

**Comment by chopmann** [comment]
@brocaar maybe use the prometheus endpoint. The rest should be alert manager stuff.

**Comment by brocaar** [comment]
I'm closing this issue. In the last releases there have been some improvements (e.g. org dashboard). I'm not planning to implement alerting etc. into ChirpStack. I think other tools (Grafana, Prometheus, ...) are better at this job as they provide a wide range of integrations (email, pushover, pagerduty, ...).
