### ISSUE TITLE
Gateway and sensor statistics 

### ISSUE THREAD

**Issue by johnjoelanders** [brocaar/chirpstack-network-server#369]
feature request

Do you plan on having a tab of some sort to display gateway statistics like eg no packet reveiced, no of join request, Total Join Responses,duplicate join request etc

Also the same for sensors like total eg number of message received , rssi max/min/avg , fcnt , number of packet up/down etc

I think something like this would be very helpful to have

thanks

**Comment by brocaar** [comment]
> Do you plan on having a tab of some sort to display gateway statistics like eg no packet reveiced, no of join request, Total Join Responses,duplicate join request etc

> no of packets received / sent is already implemented :-)

In general this is why I implemented https://github.com/brocaar/loraserver/blob/master/internal/storage/metrics.go, which is now also used for the gateway stats (number of rx and tx packets). These functions should make it possible to add additional metrics.

If you would like to contribute, then I think RX / TX stats (counters) per device would be a nice one to start with :-)
