### ISSUE TITLE
Monitor Duty Cycle On Gateways

### ISSUE THREAD

**Issue by tomaql** [brocaar/chirpstack-network-server#370]
### Is this a bug or a feature request?
Feature Request

### What did you expect?
I need a way to monitor the duty cycle on a given gateway.

We currently monitor them using the last seen at to ensure they are still alive but need something more robust.

### What happened?
Nothing

### What version are your using?
Latest

**Comment by brocaar** [comment]
Currently this information is not exposed by the packet-forwarder. Some work is being done on new packet-forwarders (e.g. the new Semtech packet-forwarder) which could facilitate this. In my opinion, the duty-cycle needs to be calculated by the gateway, not the network-server.

**Comment by queifaro** [comment]
Hello,
are some implementation (over UDP packet forwarder) already done on this feature ? or is the feature in plan for the future ?

Thanks 
Best
Fabio

**Comment by brocaar** [comment]
I have created the above issue ^^
