### ISSUE TITLE
Roaming (e.g. with TTN)

### ISSUE THREAD

**Issue by Niondir** [brocaar/chirpstack-network-server#403]
### Is this a bug or a feature request?
Feature

### What did you expect?
Getting data from Gateways registered in TTN on my Lora server instance and vice versa.

Is something in this direction planned or possible yet? I'm also not aware of the roaming state if TTN.

**Comment by brocaar** [comment]
Passive roaming has been implemented in the current `master` branch :) An other option is to use the multiplexer: https://github.com/brocaar/chirpstack-packet-multiplexer/
