### ISSUE TITLE
SkipFCntValidation Not as expected

### ISSUE THREAD

**Issue by orientlu** [brocaar/chirpstack-network-server#412]
### Is this a bug or a feature request?
bug

### What did you expect?
when device's SkipFCntValidation=true,  ns will let the uplink packet pass event though ValidateAndGetFullFCntUp retrun false.

### What happened?
but i encounter a condition which is't work as expected
In my test, device send uplinkpacket for a  long time, the fcnt in device session is  65541(32bit),
and then i reset the device.  now, the device uplinkpacket can't be handled, the error is :

``get device-session error: device-session does not exist or invalid fcnt or mic``

i found the reason is :

```go
func ValidateAndGetFullFCntUp(s DeviceSession, fCntUp uint32) (uint32, bool) {                                                                                                                                                       
    // we need to compare the difference of the 16 LSB
    gap := uint32(uint16(fCntUp) - uint16(s.FCntUp%65536))
    if gap < band.Band().GetDefaults().MaxFCntGap {
        return s.FCntUp + gap, true
    }
    return 0, false
}
```
Because : fCntUp - (0x0001 fffc % 65536) < MaxFCntGap, so  is would not run into ``if !ok {}``, and will 
reset the phyload fcnt = 65541.   result in validate mic error!!!! confuse...
```go
    fullFCnt, ok := ValidateAndGetFullFCntUp(s, macPL.FHDR.FCnt)                                                                                                                                                                 
        if !ok {
            // If RelaxFCnt is turned on, just trust the uplink FCnt
            // this is insecure, but has been requested by many people for
            // debugging purposes.
            // Note that we do not reset the FCntDown as this would reset the
            // downlink frame-counter on a re-transmit, which is not what we
            // want.
            if s.SkipFCntValidation {
//...
//...
        // the FCnt is valid, validate the MIC
        macPL.FHDR.FCnt = fullFCnt
        micOK, err := phy.ValidateUplinkDataMIC(s.GetMACVersion(), s.ConfFCnt, uint8(txDR), uint8(txCh), s.FNwkSIntKey, s.SNwkSIntKey)
```

### What version are your using?
master
### How can your issue be reproduced?
SkipFCntValidation=true; send packet(about 0x0001 ffffc), restart device;

**Comment by brocaar** [comment]
I have done some refactoring on the frame-counter validation, this might solve your issue: https://github.com/brocaar/chirpstack-network-server/commit/6b667724693070b22c49cd51f3aeabd2500a228a.
