### ISSUE TITLE
Take over an already activated OTAA device

### ISSUE THREAD

**Issue by Niondir** [brocaar/chirpstack-network-server#414]
I have a already joined OTAA devices and know the devAddr, appSessionKey and networkSessionKey.

Whats the way to join them? Is there any API or do I have to add the data to the device_activation table my self? If I do do, is there anything else to to?

**Update:** Just intersting into as and ns device_activation table seems not to be sufficient.

**Update 2:** I'm one step further. It seems I have to add the data to redis as `lora:ns:device:<devEUI>` but the value seems to be binary encoded and it's impossible to set the data by hand. So I guess we need some tool support.

**Update 3:** Just found this, maybe it would have helped me: `chirpstack-network-server print-ds 0102030405060708`

**Comment by brocaar** [comment]
This has been implemented in one of the latest ChirpStack Application Server releases. Like with ABP devices, you can set the session-keys of an OTAA device.
