### ISSUE TITLE
Introduce the possibility to find entities

### ISSUE THREAD

**Issue by eugeneugrevatov** [brocaar/chirpstack-network-server#432]
### Is this a bug or a feature request?
Feature

### What did you expect?
I would be very useful to introduce `findAll`/`findByIds` API methods for NetworkServerService

In case of implementing custom Application Server, it is impossible to get, for example, a list of devices created via NetworkServerService API. 
The workarounds are:
 - persist same data as NS would persist to have the ability to query it
 - or query straight NS database

Both don't look very neat. Simple `findAll` will be very useful :)

**Comment by brocaar** [comment]
Could you explain your use-case and why such feature would be useful?

**Comment by eugeneugrevatov** [comment]
@brocaar Hi, description updated.

And one more use-case - fetch all ABP activated devices with activation. It needs to Redis be queried and proprietary format message is parsed. Doesn't look neat either)

So IMO such feature should be presented. Thanx in advance.

**Comment by brocaar** [comment]
I'm closing this issue. Currently I'm not planning to support a search feature. The reason for this is that it would require additional indices for the fields you want to search on, which has impact on the performance.

One option that I could see useful is to add key-value attributes to objects, but this would not serve the "fetch all ABP activated devices with activation" use-case.
