### ISSUE TITLE
Importing this project to use api/gw/gw.proto structs

### ISSUE THREAD

**Issue by colthreepv** [brocaar/chirpstack-network-server#449]
### Is this a bug or a feature request?
Not sure

### What did you expect?
Be able to `import "github.com/brocaar/chirpstack-network-server/v3"`

### What happened?
```shell
$ go get
cannot load github.com/brocaar/chirpstack-network-server/v3: module github.com/brocaar/chirpstack-network-server@latest found (v2.5.0+incompatible), but does not contain package github.com/brocaar/chirpstack-network-server/v3
```

### What version are your using?
I would like to use latest `v3.4.1` that should be modules-compatible

### How can your issue be reproduced?
From an external project, import this one.

Querying go list returns
```shell
$ go list -m -versions github.com/brocaar/loraserver
github.com/brocaar/loraserver v1.0.0 v1.0.1 v2.0.0-alpha.1+incompatible v2.0.0-test.1+incompatible v2.0.0+incompatible v2.0.1+incompatible v2.0.2+incompatible v2.1.0+incompatible v2.2.0+incompatible v2.3.0+incompatible v2.3.1+incompatible v2.4.0+incompatible v2.4.1+incompatible v2.5.0+incompatible
```
I am not sure what `go list` queries to return this list, but it should be updated with most recent versions

**Comment by brocaar** [comment]
I have create https://github.com/brocaar/chirpstack-api/issues/2 because I'm moving over the API files to a separate repo to clean up dependencies + to have one dedicated repo to create API bindings for different languages.

For now you can use the loraserver@COMMITHASH as version, which should work.
