### ISSUE TITLE
Can't build network server  3.4.1 

### ISSUE THREAD

**Issue by alfonzodi** [brocaar/chirpstack-network-server#452]
Hi,

After i installed all dependencies for building  the lora network server, i'm blocked with this error  : 

make build => 

![lora_network](https://user-images.githubusercontent.com/57092573/68677273-1bd07d80-055c-11ea-9203-91ac8cc3376f.PNG)

some one have the already the same error ? thanks

**Comment by brocaar** [comment]
Please use the Docker Compose environment as a starting point. This will create a clean development environment with the required dependencies and settings.

The following commands work fine for me:

```
# rebuild 
docker-compose build

# enter docker dev. environment
docker-compose run --rm chirpstack-network-server bash

# within docker dev. env.
make
```

You can also use the `Dockerfile-devel` to as an example to setup your non-Docker dev. environment.
