### ISSUE TITLE
How to send Multicast data?

### ISSUE THREAD

**Issue by dongxusong** [brocaar/chirpstack-network-server#455]
### Is this a bug or a feature request?
I can't send data by multicast.
### What did you expect?
I can't send data by multicast, please see the picture. if the configuration is right?
### What happened?
I can't send data by multicast, please see the picture.
### What version are you using?
Lorawan mac 1.0.2
![WeChat Image_20191118180806](https://user-images.githubusercontent.com/25677385/69031809-14631580-0a2f-11ea-825d-1e5f8a21326b.png)
![WeChat Image_20191118180836](https://user-images.githubusercontent.com/25677385/69031826-1a58f680-0a2f-11ea-93ae-b00deaa8de37.png)
![WeChat Image_20191118180843](https://user-images.githubusercontent.com/25677385/69031836-1e851400-0a2f-11ea-9178-25df26e5dded.png)
![WeChat Image_20191118180851](https://user-images.githubusercontent.com/25677385/69031844-22189b00-0a2f-11ea-90a6-585b76e2b3cc.png)

### Could you share your log output?
yes

**Comment by brocaar** [comment]
I'm closing this issue, it is better to ask questions on the forum: https://forum.chirpstack.io/search?q=multicast.
