### ISSUE TITLE
[i18n] Translate

### ISSUE THREAD

**Issue by Quenty31** [brocaar/chirpstack-network-server#458]
Hello, I would like to contribute by translating.
How do I do so?

**Comment by brocaar** [comment]
I think this issue should have been created for the ChirpStack Application Server repo, as it provides the web-interface. Although I do appreciate your offer to help translating, this would require:

* A refactor of the ChirpStack Application Server web-interface to support multi-language
* Enough people willing to continuously make translation updates

Before we should offer this, I think for both the above points, we would need resources from the community as this will be a continuously effort. I think having a web-interface in a single language is still better than a releasing half-translated software.

Would you mind starting a discussion for this on the forum (https://forum.chirpstack.io) to see how much interested there would be for this?
