### ISSUE TITLE
License for more than 128 nodes ?

### ISSUE THREAD

**Issue by mout551** [brocaar/chirpstack-network-server#466]
Hi everybody,
i would like to know if chirpstack network server needs a licence for a commercial use ? 

For example, RAK7249 has a built-in loraserver which need a license if there are more than 128 nodes (https://store.rakwireless.com/collections/lorawan-gateways-concentrators/products/rak7249-diy-outdoor-gateway).

Thanks in advance. 
Erwan

**Comment by Safrone** [comment]
This project uses the MIT license: https://github.com/brocaar/chirpstack-network-server/blob/master/LICENSE 

No license required for commercial use.
