### ISSUE TITLE
Add Grafana dashboard for the existing prometheus metrics

### ISSUE THREAD

**Issue by rdresy** [brocaar/chirpstack-network-server#468]
### Is this a bug or a feature request?
Feature
### What is it about?
Gather all the metrics available on Chirpstack with Prometheus
Make the dashboard directly accessible by adding it in the docker compose

**Comment by brocaar** [comment]
I'm not planning to add / maintain such dashboards. However feel free to share your dashboards on the forum with the rest of the community :-)
