### ISSUE TITLE
Change ISM band common name instead channel plan. 

### ISSUE THREAD

**Issue by sophiekovalevsky** [brocaar/chirpstack-network-server#475]
### Is this a bug or a feature request?
Neither of both. Contribution.

### What did you expect?

- Update the way how ISM bands are configured. Instead of use the already deprecated channel plan use common name instead. 

### What happened?

If you take a closer look at: 

https://github.com/brocaar/lorawan/blob/6095d473cf605ce4da4584ae2b570bca8e1259ff/band/band.go#L35

These common names are deprecated which I think it means that this sort of assigment when referring to bands, should be avoidable in near future and be replaced by:

https://github.com/brocaar/lorawan/blob/6095d473cf605ce4da4584ae2b570bca8e1259ff/band/band.go#L49

### What version are your using?
v3.8.1

### What solutions do you propose?

If you are planning to do this eventually, I will be glad to help you on this. In this sense, I proposed the following changes:

- Update configuration within [main site.](https://www.chirpstack.io/network-server/install/config/) so that new users can use this option.
- Update default values at viper level. 
- Update configuration examples at gateways-os and docker images level.

If there is anyother missing source that you think of I am missing, let me know.

**Comment by brocaar** [comment]
Yes, you are right, it would be good to change this :) As https://github.com/brocaar/lorawan/blob/master/band/band.go#L609 already supports both the old and new naming, it should already work with the common names I believe. This means that changing the examples would not break any existing deployments.

Besides the documentation, config examples for the Gateway OS and Docker images, there is also this configuration: https://github.com/brocaar/chirpstack-network-server/tree/master/packaging/files (part of the `.deb` packages).
