### ISSUE TITLE
Support multiple server address for redis cluster

### ISSUE THREAD

**Issue by JohnRoesler** [brocaar/chirpstack-network-server#486]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-application-server/issues) of this repository and believe that this is not a duplicate.

## What is the use-case?

The underlying redis library accepts a `[]string` for server addresses, while the current config only allows for one address. For a redis cluster connection to be HA, the configuration needs to accept multiple addresses so that in the event of a cluster failover due to a node going down, the connection can use a different redis node.

## Implementation description

```
Redis settings
#
# Please note that Redis 2.6.0+ is required.
[redis]
# Redis server or servers...
servers=[
    “10.10.10.10”, “10.10.10.11”
]

password=“bar”

database=0

# Redis Cluster.
#
# Set this to true when the provided URL is pointing to a Redis Cluster 
# instance.
cluster=false

# The master name.
#
# Set the master name when the provided URL is pointing to a Redis Sentinel
# instance.
master_name=""

# Connection pool size.
#
# Default is 10 connections per every CPU.
pool_size=0
```

Should this still accept / support the prior `url=` setting and optionally parse that if it's provided for a non-cluster config? Or should that setting go away in favor of these new settings?

## Can you implement this by yourself and make a pull request?
yes

**Comment by brocaar** [comment]
This was implemented in #491
