### ISSUE TITLE
Getting error like "unknown channel for frequency: 867700000" in network server

### ISSUE THREAD

**Issue by nikhil-kumawat-1991** [brocaar/chirpstack-network-server#497]
I am running chirpstack server on one of the azure vm . I am following the below to run chirpstack server:
**https://github.com/brocaar/chirpstack-docker**

I am able to run application server as well as i have configured service profiles and device profile and also created gateway and application along with device. 

I am using OTAA to make a join-request.

For Lorawan data I am using a lds simulator for sending the data on mqtt broker.
**https://github.com/iegomez/lds/tree/0.2.0**

using this simulator, after connecting to mqtt, I tried to make a join request and below is the log for mqtt broker:
`gateway/6095ceffff5000a5/event/up {"phyPayload":"AAIAAAAAAAAAAQAAAAAAAAAAAPvorXA=","txInfo":{"frequency":867700000,"modulation":"LORA","loRaModulationInfo":{"bandwidth":125,"spreadingFactor":10,"codeRate":"4/5","polarizationInversion":false}},"rxInfo":{"gatewayID":"YJXO//9QAKU=","time":"2020-08-28T09:13:31.410270749Z","timeSinceGPSEpoch":"9223372036.854775807s","rssi":-57,"loRaSNR":7,"channel":0,"rfChain":1,"board":0,"antenna":0,"location":null,"fineTimestampType":"NONE","context":"AAAAAA=="}}`

On network-server while checking the logs I found the error:
`time="2020-08-28T09:01:24Z" level=info msg="uplink: frame(s) collected" ctx_id=dfd26df1-d088-4e93-9250-edaf02bf536f mtype=JoinRequest uplink_ids="[00000000-0000-0000-0000-000000000000]"
time="2020-08-28T09:01:24Z" level=info msg="sent uplink meta-data to network-controller" ctx_id=dfd26df1-d088-4e93-9250-edaf02bf536f dev_eui=0000000000000001
time="2020-08-28T09:01:24Z" level=info msg="device-queue flushed" ctx_id=dfd26df1-d088-4e93-9250-edaf02bf536f dev_eui=0000000000000001
time="2020-08-28T09:01:24Z" level=info msg="device-session saved" ctx_id=dfd26df1-d088-4e93-9250-edaf02bf536f dev_addr=0198d27f dev_eui=0000000000000001
time="2020-08-28T09:01:24Z" level=info msg="device-activation created" ctx_id=dfd26df1-d088-4e93-9250-edaf02bf536f dev_eui=0000000000000001 id=7
time="2020-08-28T09:01:24Z" level=info msg="device updated" ctx_id=dfd26df1-d088-4e93-9250-edaf02bf536f dev_eui=0000000000000001
time="2020-08-28T09:01:24Z" level=error msg="uplink: processing uplink frame error" ctx_id=dfd26df1-d088-4e93-9250-edaf02bf536f error="run join-response flow error: get rx1 frequency error: lorawan/band: unknown channel for frequency: 867700000"
`

Config file of lds simulator is : 
`log_level = "info"

[mqtt]
  server = "tcp://chirpstack-server-ip:1883"
  user = ""
  password = ""
  # Uplink topic. %s will be replaced with the gateway mac.
  uplink_topic="gateway/%s/event/up"
  # Downlink topic. %s will be replaced with the gateway mac.
  downlink_topic="gateway/%s/command/down"

[gateway]
  mac = "6095ceffff5000a5"

[band]
  name = "EU_863_870"

[device]
eui="0000000000000001"
address="00000000"
network_session_encription_key="dc5351f56794ed3ac17c382927192858"
serving_network_session_integrity_key="dc5351f56794ed3ac17c382927192858"
forwarding_network_session_integrity_key="dc5351f56794ed3ac17c382927192858"
application_session_key="7b14565ba0e30d6ced804393fd6a0dd5"
marshaler="json"
nwk_key="00000000000000010000000000000001"
app_key="00000000000000010000000000000001"
join_eui="0000000000000002"
mac_version=1
profile="OTAA"
joined=false
skip_fcnt_check=true

[data_rate]
  bandwith = 125
  spread_factor = 10
  bit_rate = 0

[rx_info]
  channel = 0
  code_rate = "4/5"
  crc_status = 1
  frequency = 867700000
  lora_snr = 7.0
  rf_chain = 1
  rssi = -57

[raw_payload]
  payload = "ff00"
  use_raw = false
  script = "\n// Encode encodes the given object into an array of bytes.\n//  - fPort contains the LoRaWAN fPort number\n//  - obj is an object, e.g. {\"temperature\": 22.5}\n// The function must return an array of bytes, e.g. [225, 230, 255, 0]\nfunction Encode(fPort, obj) {\n\treturn [\n      obj[\"Flags\"],\n      obj[\"Battery\"],\n      obj[\"Light\"],\n    ];\n}\n"
  use_encoder = true
  max_exec_time = 500
  js_object = "{\n \"Flags\": 0,\n \"Battery\": 65,\n \"Light\": 54\n}"
  fport = 2

[[encoded_type]]
  name = "Flags"
  value = 5.0
  max_value = 255.0
  min_value = 0.0
  is_float = false
  num_bytes = 1

[[encoded_type]]
  name = "Batería"
  value = 80.0
  max_value = 255.0
  min_value = 0.0
  is_float = false
  num_bytes = 1

[[encoded_type]]
  name = "Luz"
  value = 50.0
  max_value = 255.0
  min_value = -0.0
  is_float = false
  num_bytes = 1

[redis]
  addr = "localhost:6379"
  password = ""
  db = 10

[window]
  width = 1200
  height = 800
`

In Lorawan frames I can see an UPLINK(Join request):
![image](https://user-images.githubusercontent.com/44700017/91544825-ead00680-e93d-11ea-8c69-da72c6499956.png)

But due to the above frequency error, i am not able to see any downlink

For Lora data simulator I followed the below process:
`CHIRSPSTACK SET-TUP
(for newbie like me)

In your favorit browser go to your chirpstack app (on my case my AWS EC2 instance) port 8080
http ://xx.xx.xx.xx:8080/

login then create a network-server, organization (optional) as per the chirpstack’s getting started

Service profile:
add gateway meta-data: checked
Enable network geolocation: unchecked
Device-status request frequency: 0
Minimum allowed data-rate: 0
Maximum allowed data-rate: 5

Device Profile:
give an arbitrary name
LoRaWAN MAC version: 1.0.0
LoRaWAN Regional Parameters revision: A
Max EIRP: 0
Geolocation buffer TTL (seconds): 0
Geolocation minimum buffer size: 5

Gateways
Create
give an arbitrary name and description
generate a Gateway ID (refresh icon)
select the network server you created
no need to fill gateway profile
create gateway

Application
Create
give an arbitrary name and description
select the service profile you created

navigate to application (once more)
click on your application freshly created
on “device” click create
give an arbitrary name and description
generate a device EUI then click on MSB and keep that ID for later (be sure to keep it on MSB format) {1}
select the device profile you created
disable frame counter validation: checked
click create device

device page (you get their by finishing the above instruction by going to application->devices and selecting it)
click on Keys (OTAA)
Generated “Application key” and “Gen Application key” although we won’t need the later (refresh icon)
keep the “application key” for later IN LSB format {2}
click Set Device Keys

LORASERVER DEVICE SIMULATOR CONFIGURATION

Now, back to (in my case) Ubuntu on VMware go to the location of the “gui” executable (loraserver_device_simulator (lds) folder)
gedit conf.toml (gedit, vim, vscode, nano, whatever) to edit the lds configuration file

[mqtt]
server: tcp://theIpOfYourChirpstackServer:1883
user: “”
password: “” (I did not set these on my chirpstack app, will do later)
uplink_topic and down_link topic : leave it as it is

[device]
eui = put the MSB eui of your device that you saved in {1}
adress = “00000000” (can be anything, it does no matter just respect the size (number of 0))
network_session_encription_key=“00000000000000000000000000000000” (can be anything, it does no matter just respect the size (number of 0))
serving_network_session_integrity_key=“00000000000000000000000000000000” (can be anything, it does no matter just respect the size (number of 0))
forwarding_network_session_integrity_key=“00000000000000000000000000000000” (can be anything, it does no matter just respect the size (number of 0))
application_session_key=“00000000000000000000000000000000” (can be anything, it does no matter just respect the size (number of 0))
marshaler=“json”
nwk_key=put the LSB App Key of your device that you saved in {2}
app_key=put the LSB App Key of your device that you saved in {2}
join_eui=“0000000000000000” (can be anything, it does no matter just respect the size (number of 0))
mac_version=0
profile=“OTAA”
joined=false
skip_fcnt_check=true

save and close

TEST

on Chirpstack app (http ://xx.xx.xx.xx:8080/)
navigate to you device
navigate to Lorawan Frames

launch the lds gui application (Ubuntu)
$ ./gui
click on “Connect” MQTT & Gateway section
you should see “connection established” in Output section
click on Join in device section

on Chirpstack app (http ://xx.xx.xx.xx:8080/)
you should see a UPLINK (JoinRequest) and DOWNLINK (JoinAccept) message appearing

on lds gui application (Ubuntu)
click on “send data” in data section

on Chirpstack app (http ://xx.xx.xx.xx:8080/)
got to “activation tab” and verify that you have received the network session key and application session key
got to device data and there you will be able to see the the data you send from lds gui (Ubuntu) by clicking again “send data”.`

**Comment by brocaar** [comment]
Please see:
https://www.chirpstack.io/network-server/install/config/

You need to uncomment:

```toml
  # Extra channel configuration.
  #
  # Use this for LoRaWAN regions where it is possible to extend the by default
  # available channels with additional channels (e.g. the EU band).
  # The first 5 channels will be configured as part of the OTAA join-response
  # (using the CFList field).
  # The other channels (or channel / data-rate changes) will be (re)configured
  # using the NewChannelReq mac-command.
  #
  # Example:
  # [[network_server.network_settings.extra_channels]]
  # frequency=867100000
  # min_dr=0
  # max_dr=5

  # [[network_server.network_settings.extra_channels]]
  # frequency=867300000
  # min_dr=0
  # max_dr=5

  # [[network_server.network_settings.extra_channels]]
  # frequency=867500000
  # min_dr=0
  # max_dr=5

  # [[network_server.network_settings.extra_channels]]
  # frequency=867700000
  # min_dr=0
  # max_dr=5

  # [[network_server.network_settings.extra_channels]]
  # frequency=867900000
  # min_dr=0
  # max_dr=5
```
