### ISSUE TITLE
ChirpStack Network Server: [ERROR]:gateway: handle gateway stats error?

### ISSUE THREAD

**Issue by leesky20116** [brocaar/chirpstack-network-server#501]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?
When the gateway link to the server,network-server shows:
WARN[1603] creating insecure application-server client   server="chirpstack-application-server:8001"
ERRO[1604] gateway: handle gateway stats error           ctx_id=ed6675c2-5c37-40dd-a0be-fdbb559ded48 error="get application-server client error: get application-server client error: create application-server api client error: dial application-server api error: context deadline exceeded"
## What did you expect?
fiexed this problem
## Steps to reproduce this issue

Steps:

1.
2.
3.
4.

## Could you share your log output?
INFO[1603] gateway/mqtt: gateway stats packet received   gateway_id=b827ebfffed33e13 stats_id=ed6675c2-5c37-40dd-a0be-fdbb559ded48
INFO[1603] gateway updated                               ctx_id=ed6675c2-5c37-40dd-a0be-fdbb559ded48 gateway_id=b827ebfffed33e13
WARN[1603] creating insecure application-server client   server="chirpstack-application-server:8001"
ERRO[1604] gateway: handle gateway stats error           ctx_id=ed6675c2-5c37-40dd-a0be-fdbb559ded48 error="get application-server client error: get application-server client error: create application-server api client error: dial application-server api error: context deadline exceeded"

```shell

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v?.?.?  |
| Network Server      |         |
| Gateway Bridge      |         |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
> dial application-server api error: context deadline exceeded

You see this error since the NS can not connect to the AS.
