### ISSUE TITLE
Add nonofficial KZ 865-869 MHz ISM Band

### ISSUE THREAD

**Issue by b00bl1k** [brocaar/chirpstack-network-server#506]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## Summary

Add experimental ISM band for Kazakhstan.

## Implementation description

[LoRaWAN Regional Parameters v1.1rB_draft5 kz.pdf](https://github.com/brocaar/chirpstack-network-server/files/5421364/LoRaWAN.Regional.Parameters.v1.1rB_draft5.kz.pdf)

**Comment by brocaar** [comment]
I'll add new bands as soon as they become official. It is better to keep a personal fork with experimental band conf and create a pull-request as soon the configuration has been accepted and officially released.
