### ISSUE TITLE
Feature: number of processed events (metric)

### ISSUE THREAD

**Issue by chopmann** [brocaar/chirpstack-network-server#507]
- [x ] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## Summary
analogue to the counter `backend_mqtt_event_count` an NS instace should record how many events were actually processed by it, independent of the backend used. 

If an MQTT-Broker with `$share` topic is used, the  `backend_mqtt_event_count` might give insight how the instances are performing, but if the broker does not provide this feature or a different backend is used, you have to resort to cpu/memory metrics to infer the load on a given instance. 

## What is the use-case?
1. Provide instance utilization and detect possible "mostly winning lock" instances.

## Implementation description
Adding counters to the corresponding handlers in: https://github.com/brocaar/chirpstack-network-server/tree/master/internal/uplink

## Can you implement this by yourself and make a pull request?
Yes

**Comment by brocaar** [comment]
I agree this would be a good metric to have. If you could provide a PR for this, that would be great :)
