### ISSUE TITLE
The retransmission of confirmed downlink message does not work.

### ISSUE THREAD

**Issue by aji-iwashi** [brocaar/chirpstack-network-server#513]
- [ x ] The issue is present in the latest release.
- [ x ] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?
When the LoRaWAN device running in confirmed mode fails to receive a downlink message(FRMpayload + ACK) and is in a state of repeated retransmissions, an ACK-only unconfirmd downlink message with a different frame counter value is returned.
As with Issue #502, I used netvox R718A as the LoRa device.

## What did you expect?
While retransmission of the uplink message is taking place, the same downlink message with FRMpayload should be retransmitted several times..

## Steps to reproduce this issue

Steps:

1. Configure confirmed downlink message for Netvox R718A from Application Server GUI.
2. Send  confirmed uplink message from Netvox R718A.
3. Network Server returns the confirmed downlink message.
4. Resend the same confirmed uplink message because Netvox R718A fails to receive.
5. Network Server returns unconfirmed downlink message(ACK only ) with different frame counter value.

## Could you share your log output?
Please also fix "time": null," in the log below.

[
    {
        "downlinkMetaData": {
            "gatewayID": "000080029c0c0a8d",
            "txInfo": {
                "frequency": 923200000,
                "power": 14,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 10,
                    "codeRate": "4/5",
                    "polarizationInversion": true
                },
                "board": 0,
                "antenna": 0,
                "timing": "DELAY",
                "delayTimingInfo": {
                    "delay": "1s"
                },
                "context": "QRXZvA=="
            }
        },
        "phyPayload": {
            "mhdr": {
                "mType": "UnconfirmedDataDown",
                "major": "LoRaWANR1"
            },
            "macPayload": {
                "fhdr": {
                    "devAddr": "0000270a",
                    "fCtrl": {
                        "adr": true,
                        "adrAckReq": false,
                        "ack": true,
                        "fPending": false,
                        "classB": false
                    },
                    "fCnt": 32,
                    "fOpts": null
                },
                "fPort": 0,
                "frmPayload": [
                    {
                        "cid": "NewChannelReq",
                        "payload": {
                            "chIndex": 2,
                            "freq": 922800000,
                            "maxDR": 5,
                            "minDR": 0
                        }
                    },
                    {
                        "cid": "NewChannelReq",
                        "payload": {
                            "chIndex": 3,
                            "freq": 923000000,
                            "maxDR": 5,
                            "minDR": 0
                        }
                    },
                    {
                        "cid": "NewChannelReq",
                        "payload": {
                            "chIndex": 4,
                            "freq": 923600000,
                            "maxDR": 5,
                            "minDR": 0
                        }
                    }
                ]
            },
            "mic": "d7c77bbc"
        }
    },
    {
        "uplinkMetaData": {
            "rxInfo": [
                {
                    "gatewayID": "AACAApwMCo0=",
                    "time": null,     
                    "timeSinceGPSEpoch": null,
                    "rssi": -41,
                    "loRaSNR": 12.5,
                    "channel": 2,
                    "rfChain": 0,
                    "board": 0,
                    "antenna": 0,
                    "location": {
                        "latitude": 0,
                        "longitude": 0,
                        "altitude": 0,
                        "source": "UNKNOWN",
                        "accuracy": 0
                    },
                    "fineTimestampType": "NONE",
                    "context": "QRXZvA==",
                    "uplinkID": "/1+1s91RTl6ce3/q3uId2Q==",
                    "crcStatus": "CRC_OK"
                }
            ],
            "txInfo": {
                "frequency": 923200000,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 10,
                    "codeRate": "4/5",
                    "polarizationInversion": false
                }
            }
        },
        "phyPayload": {
            "mhdr": {
                "mType": "ConfirmedDataUp",
                "major": "LoRaWANR1"
            },
            "macPayload": {
                "fhdr": {
                    "devAddr": "0000270a",
                    "fCtrl": {
                        "adr": true,
                        "adrAckReq": false,
                        "ack": false,
                        "fPending": false,
                        "classB": false
                    },
                    "fCnt": 15922,
                    "fOpts": null
                },
                "fPort": 6,
                "frmPayload": [
                    {
                        "bytes": "fOJYPmtSwq1uvDY="
                    }
                ]
            },
            "mic": "9b5e967a"
        }
    },
    {
        "downlinkMetaData": {
            "gatewayID": "000080029c0c0a8d",
            "txInfo": {
                "frequency": 923200000,
                "power": 14,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 10,
                    "codeRate": "4/5",
                    "polarizationInversion": true
                },
                "board": 0,
                "antenna": 0,
                "timing": "DELAY",
                "delayTimingInfo": {
                    "delay": "1s"
                },
                "context": "QPm4LA=="
            }
        },
        "phyPayload": {
            "mhdr": {
                "mType": "UnconfirmedDataDown",
                "major": "LoRaWANR1"
            },
            "macPayload": {
                "fhdr": {
                    "devAddr": "0000270a",
                    "fCtrl": {
                        "adr": true,
                        "adrAckReq": false,
                        "ack": true,
                        "fPending": false,
                        "classB": false
                    },
                    "fCnt": 31,
                    "fOpts": null
                },
                "fPort": 0,
                "frmPayload": [
                    {
                        "cid": "NewChannelReq",
                        "payload": {
                            "chIndex": 2,
                            "freq": 922800000,
                            "maxDR": 5,
                            "minDR": 0
                        }
                    },
                    {
                        "cid": "NewChannelReq",
                        "payload": {
                            "chIndex": 3,
                            "freq": 923000000,
                            "maxDR": 5,
                            "minDR": 0
                        }
                    },
                    {
                        "cid": "NewChannelReq",
                        "payload": {
                            "chIndex": 4,
                            "freq": 923600000,
                            "maxDR": 5,
                            "minDR": 0
                        }
                    }
                ]
            },
            "mic": "f805e6a8"
        }
    },
    {
        "uplinkMetaData": {
            "rxInfo": [
                {
                    "gatewayID": "AACAApwMCo0=",
                    "time": null,
                    "timeSinceGPSEpoch": null,
                    "rssi": -41,
                    "loRaSNR": 11,
                    "channel": 2,
                    "rfChain": 0,
                    "board": 0,
                    "antenna": 0,
                    "location": {
                        "latitude": 0,
                        "longitude": 0,
                        "altitude": 0,
                        "source": "UNKNOWN",
                        "accuracy": 0
                    },
                    "fineTimestampType": "NONE",
                    "context": "QPm4LA==",
                    "uplinkID": "XSQS9r2pRByYfZfxQttFYA==",
                    "crcStatus": "CRC_OK"
                }
            ],
            "txInfo": {
                "frequency": 923200000,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 10,
                    "codeRate": "4/5",
                    "polarizationInversion": false
                }
            }
        },
        "phyPayload": {
            "mhdr": {
                "mType": "ConfirmedDataUp",
                "major": "LoRaWANR1"
            },
            "macPayload": {
                "fhdr": {
                    "devAddr": "0000270a",
                    "fCtrl": {
                        "adr": true,
                        "adrAckReq": false,
                        "ack": false,
                        "fPending": false,
                        "classB": false
                    },
                    "fCnt": 15922,
                    "fOpts": null
                },
                "fPort": 6,
                "frmPayload": [
                    {
                        "bytes": "fOJYPmtSwq1uvDY="
                    }
                ]
            },
            "mic": "9b5e967a"
        }
    },
    {
        "downlinkMetaData": {
            "gatewayID": "000080029c0c0a8d",
            "txInfo": {
                "frequency": 923400000,
                "power": 14,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 10,
                    "codeRate": "4/5",
                    "polarizationInversion": true
                },
                "board": 0,
                "antenna": 0,
                "timing": "DELAY",
                "delayTimingInfo": {
                    "delay": "1s"
                },
                "context": "QN7PbA=="
            }
        },
        "phyPayload": {
            "mhdr": {
                "mType": "ConfirmedDataDown",
                "major": "LoRaWANR1"
            },
            "macPayload": {
                "fhdr": {
                    "devAddr": "0000270a",
                    "fCtrl": {
                        "adr": true,
                        "adrAckReq": false,
                        "ack": true,
                        "fPending": true,
                        "classB": true
                    },
                    "fCnt": 30,
                    "fOpts": null
                },
                "fPort": 6,
                "frmPayload": [
                    {
                        "bytes": "7rvVOypB5wQ4Z0g="
                    }
                ]
            },
            "mic": "902d117a"
        }
    },
    {
        "uplinkMetaData": {
            "rxInfo": [
                {
                    "gatewayID": "AACAApwMCo0=",
                    "time": null,
                    "timeSinceGPSEpoch": null,
                    "rssi": -42,
                    "loRaSNR": 11.3,
                    "channel": 3,
                    "rfChain": 0,
                    "board": 0,
                    "antenna": 0,
                    "location": {
                        "latitude": 0,
                        "longitude": 0,
                        "altitude": 0,
                        "source": "UNKNOWN",
                        "accuracy": 0
                    },
                    "fineTimestampType": "NONE",
                    "context": "QN7PbA==",
                    "uplinkID": "NvilNS9gR1egV0uMtx57xA==",
                    "crcStatus": "CRC_OK"
                }
            ],
            "txInfo": {
                "frequency": 923400000,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 10,
                    "codeRate": "4/5",
                    "polarizationInversion": false
                }
            }
        },
        "phyPayload": {
            "mhdr": {
                "mType": "ConfirmedDataUp",
                "major": "LoRaWANR1"
            },
            "macPayload": {
                "fhdr": {
                    "devAddr": "0000270a",
                    "fCtrl": {
                        "adr": true,
                        "adrAckReq": false,
                        "ack": false,
                        "fPending": false,
                        "classB": false
                    },
                    "fCnt": 15922,
                    "fOpts": null
                },
                "fPort": 6,
                "frmPayload": [
                    {
                        "bytes": "fOJYPmtSwq1uvDY="
                    }
                ]
            },
            "mic": "9b5e967a"
        }
    }
]

```shell

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v?.?.?  |
| Network Server      |         |
| Gateway Bridge      |         |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
> While retransmission of the uplink message is taking place, the same downlink message with FRMpayload should be retransmitted several times..

I have answered why I believe it should not here: https://github.com/brocaar/chirpstack-network-server/issues/502.
