### ISSUE TITLE
(low prio) make dev-requirement does not work out of box

### ISSUE THREAD

**Issue by MarekNovakACRIOS** [brocaar/chirpstack-network-server#518]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?
I used ubuntu 18.04 vanila docker to build chirpstack-network-server and when running `make dev-requirements` (after installing make itself ....), it breaks because golang is missing. Maybe adding `apt install golang` into the dev-requirements target should be considered to make this work out of box. When using ubuntu 18.04, it is even more complicated to make it work.... so maybe only 20.04+ can be marked as supported.

## What did you expect?
I expected, that `make dev-requirements` handles all the requirements for building the repository.

## Steps to reproduce this issue
Steps:

1. docker run -it --network="host" -v "$(pwd):/workdir" ubuntu:20.04
2. once you are in the docker console, clone git repository of chirpstack-network-server
3. apt install make
4. enter the cloned folder and type `make dev-requirements`

## Could you share your log output?

```shell
root@blade:/workdir/chirpstack-network-server# make dev-requirements
/bin/sh: 1: go: not found
/bin/sh: 1: go: not found
go install golang.org/x/lint/golint
make: go: Command not found
make: *** [Makefile:52: dev-requirements] Error 127

```

## Your Environment

docker run -it --network="host" -v "$(pwd):/workdir" ubuntu:20.04

+ latest release

**Comment by brocaar** [comment]
The recommended way is to use Docker Compose, the steps are explained here: https://www.chirpstack.io/network-server/community/source/. That environment uses a Dockerfile which comes with all the requirements included.
