### ISSUE TITLE
TLS Certificates Failed to Fetch

### ISSUE THREAD

**Issue by kannansks** [brocaar/chirpstack-network-server#521]
I tried to add the tls certificates and keys to the network server in the web interface however it is showing failed to fetch when i update the network server
Then i tried adding cert and key for network and application servers separately the same error occurred for network server cert and key but when i tried with only application server cert and key the network server was updated in the web interface

Could this be problem with the toml of network server??? if not what could be the reason??

**Comment by brocaar** [comment]
I'm closing this issue as it has been asked on the forum as well.
