### ISSUE TITLE
Can't set the TLS certifficates

### ISSUE THREAD

**Issue by 71GA** [brocaar/chirpstack-network-server#524]
I want to use TLS certificates on my Chirpstack.

In order to do that I `git clone` the repository (https://github.com/brocaar/chirpstack-certificates) and then build the TTL certifficates by following instructions (https://github.com/brocaar/chirpstack-certificates/blob/master/README.md). When certificates are built, they can be found in the `certs` subfolder.

Subfolder `/certs/ca` is especially interesting to me because I read in the same instructions that:

> `certs/ca`
> 
> Use the ca.pem "common authority" certificate for every API endpoint you wish to secure using TLS. The `ca.pem` and `ca-key.pem` can also be used within the ChirpStack Network Server and ChirpStack Application Server configuration for generating gateway and MQTT client certificates.

According to this citation I assume that Iit is possible to use `ca.pem` and `ca-key.pem` from the subfolder `certs/ca` to configure TLS inside the ChirpStack's web interfice. 

In order to do this I login as `admin` to the ChirpStack's web interface and in the left side menu navigate to <kbd>Network-servers</kbd>, then select a server from the list and navigate to the tab <kbd>TLS CERTIFFICATES</kbd>.

Here we can see that there are two **categories** i.e.:

- *"network server"* ⟶ *"application server"*
- *"network server"* ⟵ *"application server"*

Both categories need three **fields**:

- _"CA's TLS certificate"_
- _"TLS certificate"_
- _"TLS key"_

I paste content of `key.pem` in the **fields** _"TLS key"_ for both **components**. 
I paste content of `ca.pem` in the rest of the **fields** for both **components**.

When I press <kbd>UPDATE NETWORK-SERVER</kbd> I get this error:

`context deadline exceeded (code: 2)`

What is wrong?

**Comment by brocaar** [comment]
I have just re-tested this again, and it works fine.

Step 1:
Configure the certificates at the server-side (through the `chirpstack-network-server.toml` and `chirpstack-application-server.toml` files).

Step 2:
Configure the client-certificates through the web-interface.

Both sides need to be configured properly, as the client will validate the server and visa-versa.
