### ISSUE TITLE
Default Frequency Channel for KR920 changed?

### ISSUE THREAD

**Issue by factoryal** [brocaar/chirpstack-network-server#531]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?
Hi.
I tried to send my LoRa end device to latest version of Chirpstack network server but sometimes sending message fails.
For detail, Gateway receives all messages but there's no message on "Live LoRaWAN Frames" on device menu sometimes.
It happened super randomly so It took long time to figure out this issue.

## What did you expect?

I finally figured out that messages from only three frequences visible on "Live LoRaWAN Frames" menu. the channel number is 0, 1, 2.
I'm using KR920 frequency plan, so ch0: 922.1Mhz, ch1: 922.3Mhz, ch2: 922.5Mhz.
I manually added the rest of frequencies in the config file then it worked just normal.
I tried LoRaWAN project with Chirpstack about 2 years ago but there was nothing like this problem.
Would you check for something changes on here?

## Steps to reproduce this issue

Steps:

1. I used RAK811 LoRaWAN module.
2. I added device to chirpstack-application-server.
3. Command RAK811 to join network and send some messages.
4. Sometimes can successfully receive message, but sometimes not.
5. Only messages from three frequencies(ch0, ch1, ch2) are visible on "Device Data" menu.

## Could you share your log output?
I'm really sorry that I didn't logged the output.
But I remember that there was "unknown channel for frequency"

```shell

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v3.15.0-test1-5-g4cb2d50  |
| Network Server      |   v3.13.0-test.1-5-g65d9d63  |
| Gateway Bridge      |  v3.11.0-test.1  |
| Chirpstack API      |    ?     |
| Geolocation         |     ?    |
| Concentratord       |     ?    |

**Comment by brocaar** [comment]
> I manually added the rest of frequencies in the config file then it worked just normal.

That is a required step as ChirpStack must be aware of the channels that are used on your network. When data is received on an unknown channel, this will result in:

> unknown channel for frequency

This is expected behavior.
