### ISSUE TITLE
Access to encrypted Network Server Data

### ISSUE THREAD

**Issue by ImanIDG** [brocaar/chirpstack-network-server#537]
Hi,

Is there any chance to have access to encrypted end-device payload from network server?

I want to provide an end-to-end encrypted LoRaWAN solution for a third party organization through Chirpstack. In other word, I only want to provide LorRaWAN network platform for my costumer's own devices and APP. As I recall and checked, appSKey is only essential for decryption of end-device data payload. I want to make decryption, only available for my costumer. Is there any way to have access (like through APIs) to encrypted Network Server Data?

**Comment by brocaar** [comment]
Unless you implement your own AS interface (https://github.com/brocaar/chirpstack-api/blob/master/protobuf/as/as.proto), this is not possible currently.
