### ISSUE TITLE
Connection reset by peer (upgrade lib/pq)

### ISSUE THREAD

**Issue by andyesys** [brocaar/chirpstack-network-server#547]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?

There is an issue with the database access. After running for over a week, we start getting database "connection reset by peer" errors.

I found the issue originates in the lib/pq postgresql driver where broken idle connections are not detected. This is supposed to be fixed starting with version 1.9. Reference: original issue https://github.com/lib/pq/issues/835

**This bug also applies to the application server and must be fixed there too.**

So in order to fix this please upgrade lib/pq to the newest version here: https://github.com/brocaar/chirpstack-network-server/blob/c386dfda894952b4bdfb2e9e505ef954ab97ae7c/go.mod#L25

## What did you expect?

No connection errors. lib/pq should detect dead idle connections.

## Steps to reproduce this issue

Hard to reproduce. Try to place a firewall in between chirpstack and database and reset connections there.

## Could you share your log output?

We only have a screenshot:

![image](https://user-images.githubusercontent.com/30472657/131313532-dcd69c57-7410-4ee4-af3f-f2d1447ecd8d.png)

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v3.16.0  |
| Network Server      | v3.14.0        |
| Gateway Bridge      |  v3.12.0       |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
The above commit updates it in the ChirpStack Application Server.
