### ISSUE TITLE
Add gatewayId on joinRequest

### ISSUE THREAD

**Issue by kevinEdgeTech** [brocaar/chirpstack-network-server#568]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## Summary

I would like receive gatewayId when i use join server External.

## What is the use-case?

When we create :
- organization A with Gateway A and Device A.
- organization B with Gateway B and Device B.

if Device A send joinRequest and Gateway B receive this joinRequest.
The Network Server send joinRequest to external Join Server but Device A isn't create on same Organization.

I developed my Join Server, so i would like receive GatewayId information in JoinRequest to add a check when i receive JoinRequest if this gateway have "right" to send this JoinRequest

**Comment by brocaar** [comment]
Please note that the NS<>JS interface is specified by the LoRa Alliance and I don't believe such field exists.

Apart from that, in my opinion the JS should have no knowledge about the gateways. All it should know is if the NS requesting the join-accept has the right credentials and if the join-request is valid (MIC check, dev-nonce check etc...).

Note that within ChirpStack it is possible to make gateways private to an organization. Could it be that you are looking for this feature? if a gateway is private to an organization, only devices within the same organization are able to receive uplinks through these gateways.
