### ISSUE TITLE
Device Logs showing error message.

### ISSUE THREAD

**Issue by mudassirahmed395** [brocaar/chirpstack-network-server#576]
- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?
When I enter the device logs in chirpStack the device shows log errors.  Attached below is the picture of it.
![image](https://user-images.githubusercontent.com/100129437/154947015-910552cf-9d8a-429a-aa97-fc2a893d2c71.png)

## What did you expect?
I expect to have logs without error message as some of the log messages does not show any error message attached below.
## Steps to reproduce this issue

Steps:

1. This issues gets produce when I open the "Device Data". Sometime it produces error sometime logs are working fine so it is hard to tell what exactly is the procedure to reproduce this error.
![Uploading image.png…]()

## Could you share your log output?
[
    {
        "type": "error",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "type": "UPLINK_FCNT_RETRANSMISSION",
            "error": "frame-counter did not increment",
            "fCnt": 28,
            "tags": {},
            "publishedAt": "2022-02-21T10:38:04.688143501Z"
        }
    },
    {
        "type": "up",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "rxInfo": [
                {
                    "gatewayID": "/MI9//4LbxM=",
                    "time": null,
                    "timeSinceGPSEpoch": null,
                    "rssi": -88,
                    "loRaSNR": 8.5,
                    "channel": 1,
                    "rfChain": 1,
                    "board": 0,
                    "antenna": 0,
                    "location": {
                        "latitude": 53.74952285419751,
                        "longitude": -1.4503240585327148,
                        "altitude": 0,
                        "source": "UNKNOWN",
                        "accuracy": 0
                    },
                    "fineTimestampType": "NONE",
                    "context": "7k1gow==",
                    "uplinkID": "N/JtCSpySgGhQlVODcR77g==",
                    "crcStatus": "CRC_OK"
                }
            ],
            "txInfo": {
                "frequency": 868300000,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 7,
                    "codeRate": "4/5",
                    "polarizationInversion": false
                }
            },
            "adr": true,
            "dr": 5,
            "fCnt": 28,
            "fPort": 1,
            "data": "vcAV",
            "objectJSON": "",
            "tags": {},
            "confirmedUplink": false,
            "devAddr": "ALaHOw==",
            "publishedAt": "2022-02-21T10:38:02.397194752Z",
            "deviceProfileID": "212465e5-339f-4641-9521-e11019eb97fe",
            "deviceProfileName": "BrighterBins Fill-level Detector"
        }
    },
    {
        "type": "error",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "type": "UPLINK_FCNT_RETRANSMISSION",
            "error": "frame-counter did not increment",
            "fCnt": 27,
            "tags": {},
            "publishedAt": "2022-02-21T10:08:07.508100545Z"
        }
    },
    {
        "type": "error",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "type": "UPLINK_FCNT_RETRANSMISSION",
            "error": "frame-counter did not increment",
            "fCnt": 27,
            "tags": {},
            "publishedAt": "2022-02-21T10:08:04.580688972Z"
        }
    },
    {
        "type": "up",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "rxInfo": [
                {
                    "gatewayID": "/MI9//4LbxM=",
                    "time": null,
                    "timeSinceGPSEpoch": null,
                    "rssi": -98,
                    "loRaSNR": 5.8,
                    "channel": 5,
                    "rfChain": 0,
                    "board": 0,
                    "antenna": 0,
                    "location": {
                        "latitude": 53.74952285419751,
                        "longitude": -1.4503240585327148,
                        "altitude": 0,
                        "source": "UNKNOWN",
                        "accuracy": 0
                    },
                    "fineTimestampType": "NONE",
                    "context": "gwIhfA==",
                    "uplinkID": "JkyNjaZiRsGAmk2MuBD5Lg==",
                    "crcStatus": "CRC_OK"
                }
            ],
            "txInfo": {
                "frequency": 867500000,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 7,
                    "codeRate": "4/5",
                    "polarizationInversion": false
                }
            },
            "adr": true,
            "dr": 5,
            "fCnt": 27,
            "fPort": 1,
            "data": "vcAV",
            "objectJSON": "",
            "tags": {},
            "confirmedUplink": false,
            "devAddr": "ALaHOw==",
            "publishedAt": "2022-02-21T10:08:02.288635572Z",
            "deviceProfileID": "212465e5-339f-4641-9521-e11019eb97fe",
            "deviceProfileName": "BrighterBins Fill-level Detector"
        }
    },
    {
        "type": "error",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "type": "UPLINK_FCNT_RETRANSMISSION",
            "error": "frame-counter did not increment",
            "fCnt": 26,
            "tags": {},
            "publishedAt": "2022-02-21T09:38:07.410332491Z"
        }
    },
    {
        "type": "error",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "type": "UPLINK_FCNT_RETRANSMISSION",
            "error": "frame-counter did not increment",
            "fCnt": 26,
            "tags": {},
            "publishedAt": "2022-02-21T09:38:04.482666554Z"
        }
    },
    {
        "type": "up",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "rxInfo": [
                {
                    "gatewayID": "/MI9//4LbxM=",
                    "time": null,
                    "timeSinceGPSEpoch": null,
                    "rssi": -95,
                    "loRaSNR": -0.5,
                    "channel": 7,
                    "rfChain": 0,
                    "board": 0,
                    "antenna": 0,
                    "location": {
                        "latitude": 53.74952285419751,
                        "longitude": -1.4503240585327148,
                        "altitude": 0,
                        "source": "UNKNOWN",
                        "accuracy": 0
                    },
                    "fineTimestampType": "NONE",
                    "context": "F7bsRA==",
                    "uplinkID": "+2E+NXnPS/OIMLMsz23VnQ==",
                    "crcStatus": "CRC_OK"
                }
            ],
            "txInfo": {
                "frequency": 867900000,
                "modulation": "LORA",
                "loRaModulationInfo": {
                    "bandwidth": 125,
                    "spreadingFactor": 7,
                    "codeRate": "4/5",
                    "polarizationInversion": false
                }
            },
            "adr": true,
            "dr": 5,
            "fCnt": 26,
            "fPort": 1,
            "data": "vcAV",
            "objectJSON": "",
            "tags": {},
            "confirmedUplink": false,
            "devAddr": "ALaHOw==",
            "publishedAt": "2022-02-21T09:38:02.200842834Z",
            "deviceProfileID": "212465e5-339f-4641-9521-e11019eb97fe",
            "deviceProfileName": "BrighterBins Fill-level Detector"
        }
    },
    {
        "type": "error",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "type": "UPLINK_FCNT_RETRANSMISSION",
            "error": "frame-counter did not increment",
            "fCnt": 25,
            "tags": {},
            "publishedAt": "2022-02-21T09:08:07.507951283Z"
        }
    },
    {
        "type": "error",
        "payload": {
            "applicationID": "232",
            "applicationName": "brighter-bins-test",
            "deviceName": "production-laser-0080e11500073d52",
            "devEUI": "AIDhFQAHPVI=",
            "type": "UPLINK_FCNT_RETRANSMISSION",
            "error": "frame-counter did not increment",
            "fCnt": 25,
            "tags": {},
            "publishedAt": "2022-02-21T09:08:04.564398874Z"
        }
    }
]

```shell

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v?.?.?  |
| Network Server      |         |
| Gateway Bridge      |         |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by liangyuanpeng** [comment]
Seems like your sensor have not correct increment the `fcnt`.

**Comment by mudassirahmed395** [comment]
But device work fine in TTN Actiltiy Proimous.

**Comment by brocaar** [comment]
This is because of https://github.com/brocaar/chirpstack-network-server/issues/560.
