### ISSUE TITLE
Where do I go to change how ADR works?

### ISSUE THREAD

**Issue by HyeonHo-Jung** [brocaar/chirpstack-network-server#577]
Hello

I would like to improve the ADR of a network server.

By the way, I don't see any code related to ADR at all.

Where can I edit ADR code.

please help..

**Comment by IoTThinks** [comment]
May have some hints in the location here?
https://github.com/brocaar/chirpstack-network-server/commit/2aea7096f5036030823517fcce5a0c97021becc5#diff-828c392ee8c95158ce8c450ec266826192d7dd84be25f81095d91a75f75cd2c8
