### ISSUE TITLE
Network server does nothing

### ISSUE THREAD

**Issue by sergorl** [brocaar/chirpstack-network-server#579]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-network-server) of this repository and believe that this is not a duplicate.

## What happened?
According logs server doesn't receive any messages from gateway bridge and doesn't communicate with application server,

## What did you expect?
Server should receive some messages from gateway bridge and communicate with apllication-server.

## Steps to reproduce this issue

Steps:

1. Run [gateway simulator](https://github.com/UniCT-ARSLab/LWN-Simulator): `go run cmd/main.go`. Then create virtual gateway and launch simulation.
2. `sudo systemctl start chirpstack-gateway-bridge`
3. `sudo systemctl start chirpstack-network-server`
4. `sudo systemctl start chirpstack-application-server`

## Could you share your log output?

```shell
Apr 15 10:12:36 chirp systemd[1]: Stopping ChirpStack Network Server...
Apr 15 10:12:36 chirp systemd[1]: chirpstack-network-server.service: Succeeded.
Apr 15 10:12:36 chirp systemd[1]: Stopped ChirpStack Network Server.
Apr 15 10:12:38 chirp systemd[1]: Started ChirpStack Network Server.
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.041028535Z" level=info msg="starting ChirpStack Network Server" band=EU868 docs="https://www.chirpstack.io/" net_id=000000 version=3.16.1
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.041161955Z" level=info msg="storage: setting up storage module"
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.041177313Z" level=info msg="storage: setting up Redis client"
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.041224682Z" level=info msg="storage: connecting to PostgreSQL"
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.047737674Z" level=info msg="storage: applying PostgreSQL data migrations"
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.050344274Z" level=info msg="gateway/mqtt: connecting to mqtt broker" server="tcp://localhost:1883"
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.050955849Z" level=info msg="api: starting network-server api server" bind="127.0.0.1:8000" ca-cert= tls-cert= tls-key=
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.051109506Z" level=info msg="backend/gateway: connected to mqtt server"
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.051167505Z" level=info msg="gateway/mqtt: subscribing to gateway event topic" qos=0 topic=gateway/+/event/+
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.051241252Z" level=info msg="starting downlink device-queue scheduler"
Apr 15 10:12:39 chirp chirpstack-network-server[19752]: time="2022-04-15T10:12:39.051260038Z" level=info msg="starting multicast scheduler"

```

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  |3.17.6 |
| Network Server      | 3.16.1 |
| Gateway Bridge      |3.13.2|
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
I can not reproduce this issue. This might be an issue related to your setup or to the simulator setup. You can find debugging steps in this documentation: https://www.chirpstack.io/project/guides/connect-gateway/.
